#!/usr/bin/env bash
# Emits the PKGBUILD for the `voltius-bin` AUR package to stdout.
# Usage: gen-aur-pkgbuild.sh <tag>   e.g. gen-aur-pkgbuild.sh v0.27.0
#
# Repackages the released .deb rather than building from source: the release
# already ships x86_64 and aarch64 binaries, and a from-source AUR package would
# make every user compile the whole Rust + pnpm tree. `-bin` is the conventional
# name for that on the AUR.
#
# The .SRCINFO that must sit beside the PKGBUILD is NOT generated here — it has
# to come from `makepkg --printsrcinfo`, which needs an Arch environment. The
# publish-aur job does that step in an archlinux container.
#
# Requires: gh (authenticated), awk.
set -euo pipefail

TAG="${1:?usage: gen-aur-pkgbuild.sh <tag>}"

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/release-assets.sh"
release_assets_init "$TAG"

DEB_X86="$(release_asset amd64.deb)"
DEB_ARM="$(release_asset arm64.deb)"

SHA_X86="$(release_sha "$DEB_X86")"
SHA_ARM="$(release_sha "$DEB_ARM")"

cat <<EOF
# Maintainer: Killian Pavy <kiki.kalagan@gmail.com>
# This file is generated by scripts/gen-aur-pkgbuild.sh in VoltiusApp/voltius.
# Edit it there, not here.

pkgname=voltius-bin
_pkgname=voltius
pkgver=${VERSION}
pkgrel=1
pkgdesc="Local-first SSH/SFTP/Serial client with E2EE sync, team vaults and plugins"
arch=('x86_64' 'aarch64')
url="https://voltius.app"
license=('AGPL-3.0-or-later')
depends=('webkit2gtk-4.1' 'gtk3' 'libsecret')
optdepends=('tmux: persistent sessions that survive disconnects'
            'screen: persistent sessions that survive disconnects')
provides=("\${_pkgname}")
conflicts=("\${_pkgname}")
options=('!strip' '!debug')
source_x86_64=("\${pkgname}-\${pkgver}-x86_64.deb::https://github.com/${REPO}/releases/download/${TAG}/${DEB_X86}")
source_aarch64=("\${pkgname}-\${pkgver}-aarch64.deb::https://github.com/${REPO}/releases/download/${TAG}/${DEB_ARM}")
sha256sums_x86_64=('${SHA_X86}')
sha256sums_aarch64=('${SHA_ARM}')

package() {
  # makepkg unpacks the .deb into its members; the payload name varies with the
  # compression dpkg-deb chose, so match rather than hardcode data.tar.gz.
  local payload
  payload=\$(find "\${srcdir}" -maxdepth 1 -name 'data.tar.*' -print -quit)
  [ -n "\${payload}" ] || { echo "no data.tar.* in \${srcdir}" >&2; return 1; }

  bsdtar -xf "\${payload}" -C "\${pkgdir}"
}
EOF
