#!/usr/bin/env bash
# Emits the Flatpak manifest for Voltius to stdout.
# Usage: gen-flatpak-manifest.sh <tag>   e.g. gen-flatpak-manifest.sh v0.27.0
#
# Repackages the released .deb, same reasoning as the AUR package: the release
# already ships x86_64 and aarch64 binaries, and Flathub's builders should not
# have to compile the whole Rust + pnpm tree.
#
# Like the Scoop manifest, this is a bootstrapping tool rather than a release
# step. The manifest carries x-checker-data, so once it is merged into
# flathub/app.voltius.Voltius, Flathub's flatpak-external-data-checker bot
# follows new releases on its own — nothing here has to run again unless the
# release asset naming changes.
#
# Requires: gh (authenticated), awk.
set -euo pipefail

TAG="${1:?usage: gen-flatpak-manifest.sh <tag>}"

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/release-assets.sh"
release_assets_init "$TAG"

DEB_X86="$(release_asset amd64.deb)"
DEB_ARM="$(release_asset arm64.deb)"

SHA_X86="$(release_sha "$DEB_X86")"
SHA_ARM="$(release_sha "$DEB_ARM")"

cat <<EOF
# Generated by scripts/gen-flatpak-manifest.sh in VoltiusApp/voltius.
# Once merged into Flathub, x-checker-data keeps it current — regenerate only if
# the release asset naming changes.
app-id: app.voltius.Voltius
runtime: org.gnome.Platform
runtime-version: '50'
sdk: org.gnome.Sdk
command: voltius
separate-locales: false

finish-args:
  # WebKitGTK rendering
  - --share=ipc
  - --socket=wayland
  - --socket=fallback-x11
  - --device=dri

  # SSH, SFTP, sync relay
  - --share=network

  # Agent forwarding: reach the host's ssh-agent instead of asking for the
  # passphrase on every connection.
  - --socket=ssh-auth

  # SFTP transfers need the local side of the copy, and ~/.ssh is where users
  # already keep the keys they want to import.
  - --filesystem=home

  # Credentials go to the Secret Service (gnome-keyring, KWallet) when the user
  # picks the OS-keychain tier rather than a master password.
  - --talk-name=org.freedesktop.secrets

  # Serial console: /dev/ttyUSB*, /dev/ttyACM*. Flatpak has no narrower way to
  # expose a serial port than --device=all.
  - --device=all

  # The local-terminal feature opens the user's real shell (bash, zsh, fish,
  # ...) with their real toolchain. Without host spawn that feature silently
  # becomes "a shell inside the sandbox", which is not what it says it is. Same
  # permission the terminal emulators on Flathub carry for the same reason.
  - --talk-name=org.freedesktop.Flatpak

modules:
  - name: voltius
    buildsystem: simple
    build-commands:
      - ar x voltius.deb
      # Glob rather than data.tar.gz: the payload compression is dpkg-deb's
      # choice, not ours.
      - tar -xf data.tar.*
      - install -Dm755 usr/bin/voltius /app/bin/voltius
      # The icon basename has to match the app-id. Tauri also emits a
      # "256x256@2" directory, which is not a hicolor size (hicolor spells it
      # "@2x"), so it is skipped rather than installed under a bad name.
      - install -Dm644 usr/share/icons/hicolor/32x32/apps/voltius.png
        /app/share/icons/hicolor/32x32/apps/app.voltius.Voltius.png
      - install -Dm644 usr/share/icons/hicolor/128x128/apps/voltius.png
        /app/share/icons/hicolor/128x128/apps/app.voltius.Voltius.png
      - install -Dm644 app.voltius.Voltius.desktop
        /app/share/applications/app.voltius.Voltius.desktop
      - install -Dm644 app.voltius.Voltius.metainfo.xml
        /app/share/metainfo/app.voltius.Voltius.metainfo.xml
    sources:
      - type: file
        only-arches: [x86_64]
        url: $(release_url "$DEB_X86")
        sha256: ${SHA_X86}
        dest-filename: voltius.deb
        x-checker-data:
          type: json
          url: https://api.github.com/repos/${REPO}/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: '"https://github.com/${REPO}/releases/download/v" + \$version
            + "/Voltius_" + \$version + "_amd64.deb"'
      - type: file
        only-arches: [aarch64]
        url: $(release_url "$DEB_ARM")
        sha256: ${SHA_ARM}
        dest-filename: voltius.deb
        x-checker-data:
          type: json
          url: https://api.github.com/repos/${REPO}/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: '"https://github.com/${REPO}/releases/download/v" + \$version
            + "/Voltius_" + \$version + "_arm64.deb"'
      - type: file
        path: app.voltius.Voltius.desktop
      - type: file
        path: app.voltius.Voltius.metainfo.xml
EOF
